- name: Rulare platforma monitorizare
  hosts: valid_host
  become: true
  tasks:
    - name: Creeaza director proiect
      file:
        path: /opt/project
        state: directory
        mode: '0755'

    - name: Copiaza codul sursa
      copy:
        src: "{{ playbook_dir }}/../"
        dest: /opt/project/
        owner: root
        group: root
        mode: '0755'

    - name: Ruleaza docker-compose
      shell: docker-compose up -d
      args:
        chdir: /opt/project/
