pipeline {
    agent any

    environment {
        DOCKERHUB_CRED = credentials('dockerhub') // Username + Password
        IMAGE_NAME = "vtscorpio/backup:latest"
    }

    stages {
        stage('Lint') {
            steps {
                sh 'pipx install pylint'
                sh 'pylint /backup/backup.py'
            }
        }

        stage('Test') {
            steps {
                sh 'pipx install pytest'
                sh 'pytest /backup/test_backup.py'
            }
        }

        stage('Docker Build') {
             steps {
                 dir('backup') {
                    sh '''
                    echo "[INFO] Construim imagine Docker..."
                    docker build -t $IMAGE_NAME .
                    '''
                }
                    
            }
            
        }


        stage('Login & Push') {
            steps {
                sh "echo $DOCKERHUB_CRED_PSW | docker login -u $DOCKERHUB_CRED_USR --password-stdin"
                sh 'docker push $IMAGE_NAME'
            }
        }

    //     stage('Deploy to Minikube') {
    //     steps {
    //         script {
    //             def backupExists = sh(script: "docker images | grep backup | wc -l", returnStdout: true).trim()
    //             def monitorExists = sh(script: "docker images | grep monitor | wc -l", returnStdout: true).trim()

    //             if (backupExists != "0" && monitorExists != "0") {
    //                 sh '''
    //                 echo "[INFO] Setăm contextul Minikube..."
    //                 kubectl config use-context minikube

    //                 echo "[INFO] Aplicăm fișierele YAML pentru backup și monitor..."
    //                 kubectl apply -f k8s/monitor-deployment.yaml
    //                 kubectl apply -f k8s/backup-deployment.yaml
    //                 kubectl apply -f k8s/monitor-service.yaml
    //                 kubectl apply -f k8s/backup-service.yaml

    //                 echo "[INFO] Așteptăm finalizarea rollout-ului..."
    //                 kubectl rollout status deployment/monitor-deployment
    //                 kubectl rollout status deployment/backup-deployment

    //                 echo "[INFO] Verificare poduri active..."
    //                 kubectl get pods -o wide
    //                 '''
    //             } else {
    //                 error("[ERROR] Imaginile Docker pentru backup sau monitor lipsesc. Oprește pipeline-ul.")
    //             }
    //         }
    //     }
    // }


    }
}
